codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
        target: auto
        threshold: 1%
      frontend:
        flags:
          - frontend
      ms-order:
        flags:
          - ms-order
      ms-customer:
        flags:
          - ms-customer
      api-gateway:
        flags:
          - api-gateway
      service-discovery:
        flags:
          - service-discovery

flags:
  frontend:
    paths:
      - frontend/src
  ms-order:
    paths:
      - ms-order/src
  ms-customer:
    paths:
      - ms-customer/src
  api-gateway:
    paths:
      - api-gateway/src
  service-discovery:
    paths:
      - service-discovery/src