codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
        target: auto
        threshold: 1%
      frontend:
        flags:
          - frontend
      ms-order:
        flags:
          - ms-order
      ms-customer:
        flags:
          - ms-customer

flags:
  frontend:
    paths:
      - frontend/src
  ms-order:
    paths:
      - ms-order/src
  ms-customer:
    paths:
      - ms-customer/src
