@startuml context_diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title BTG - Diagrama de Contexto

Person(user, "Usuario", "Cliente que gerencia clientes e pedidos")

System(system, "Plataforma BTG", "Aplicacao full stack para clientes e pedidos")

System_Ext(mysql, "MySQL 8.4", "Persistencia de dados")
System_Ext(rabbitmq, "RabbitMQ", "Broker AMQP")
System_Ext(eureka, "Service Discovery", "Registro e descoberta de servicos")

Rel(user, system, "Usa", "HTTPS")

Rel(system, mysql, "Armazena dados")
Rel(system, rabbitmq, "Publica e consome eventos")
Rel(system, eureka, "Registro e descoberta de servicos")

@enduml