spring.application.name=ms-customer
spring.config.import=optional:file:.env

#spring.data.mongodb.database=client_db
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb://localhost:27017/client_db
#spring.data.mongodb.auto-index-creation=true
#spring.jpa.show-sql=true

# MYSQL
#spring.datasource.url=jdbc:mysql://${db.client.host}:3306/${db.client.name}?createDatabaseIfNotExist=true
#spring.datasource.username=${db.client.username}
#spring.datasource.password=${db.client.password}
spring.jpa.show-sql=true

#eureka.client.serviceUrl.defaultZone=${eurekaurl}
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=0

