name: ms-customer Module CI Pipelines

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  code-quality-customers:
    name: ms-customer Linting and Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Run spotless check
        run: mvn -B -f ms-customer/pom.xml spotless:check

      - name: Run Checkstyle
        run: mvn -B -f ms-customer/pom.xml checkstyle:check

      - name: Generate Checkstyle report
        run: mvn -B -f ms-customer/pom.xml checkstyle:checkstyle

      - name: Run PMD check
        run: mvn -B -f ms-customer/pom.xml pmd:check

      - name: generate PMD report
        run: mvn -B -f ms-customer/pom.xml pmd:pmd
      
      - name: Run spotbugs check
        run: mvn -B -f ms-customer/pom.xml spotbugs:check

      - name: Generate SpotBugs report
        run: mvn -B -f ms-customer/pom.xml spotbugs:spotbugs
  
  test-customers:
    needs: [code-quality-customers]
    name: ms-customer Module Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
  
      - name: Roda os testes do módulo ms-customer
        run: mvn -B -f ms-customer/pom.xml clean package

      #- name: Run E2E tests do módulo ms-customer
      #  run: mvn -B -f ms-customer/pom.xml -Ddocker.e2e=false -Dtest=CustomerFlowE2ETest test

      - name: Run Code Quality Analysis do módulo ms-customer
        run: mvn -B -f ms-customer/pom.xml jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ms-customer/target/site/jacoco/jacoco.xml
          flags: ms-customer
          name: ms-customer-coverage
          fail_ci_if_error: false
          verbose: true

      - name: Upload Coverage Report do módulo ms-customer
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: ms-customer/target/site/jacoco/
          retention-days: 1

  build-customers:
    needs: [test-customers]
    name: ms-customer Module Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build ms-customer module
        run: mvn -B -f ms-customer/pom.xml clean package -DskipTests
      
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ms-customer-jar
          path: ms-customer/target/*.jar
          retention-days: 1

  #docker:
  #  needs: build-customers
  #  uses: ./.github/workflows/docker.yml
  #  secrets: inherit
  
  #deploy_google:
  #  needs: docker
  #  uses: ./.github/workflows/release-gcloud.yml
  #  secrets: inherit